### ISSUE TITLE
continuous triggering and nextDate going backwards due to external pollution of Array.find()

### ISSUE THREAD

**Issue by Steve-Mcl** [jaclarke/cronosjs#1]
Hi, I am integrating this great library into a node-red-contrib node.

I had great success running your code outside of node-red but had problems inside node-red.

What happened was some other code had "shimmed" `Array.find()` & it was returning an index (or -1 if not found) rather than an item (or undefined if not found). 

So when `_nextSecond()` ran, it returned `-1` instead of undefined.
This caused _timestamp to decrease & thus the `timeout` value inside `runScheduledTasks()` (for setTimeout) to be a **minus value** causing your code to continuously fire the trigger (at tick rate).

While I realise this isn't a necessarily bug with your code...
* Perhaps you might consider asserting or bounds checking `setTimeout`?
* You might also want to check that  `nextSecond` is not outside of 0 ~ 59. 
* Alternatively, you might want to use lookup objects instead of Arrays?
  * e.g. if `seconds` were an a dynamically built object like... 
  ```
    this.seconds = {
      0 : 0,
     30: 30
    }
  ```
  then accessing the item becomes a simple accessor... 
  ```
    //ORIGINAL: let nextSecond = this.seconds.find(n => n >= fromDate.second); 
    let nextSecond = this.seconds[fromDate.second]; //NEW: no need to iterate - just access from object
    if (nextSecond === undefined) return null;
    ...
  ```

**Regarding the Array prototype pollution...**
I realise you cannot check every function of every library for prototype pollution however as minimum expression  * * * * * * should only trigger once per second, & I was getting continuous triggers (at tick rate). Perhaps some supervisory code could be created to ensure triggers are not happening too often?

_Just a suggestion..._
I added `expr.cronString = cronstring` to `CronosExpression.parse()` and a function `toString(){return this.cronString;}` as I found it very useful for debugging.

**Comment by jaclarke** [comment]
Thanks for the detailed description of the problem. While I'd consider the issue to belong to the code/lib modifying the Array prototype (`Array.prototype.find` and `Array.prototype.findIndex` are es6 methods, so it sounds like it may be something incorrectly polyfilling `Array.prototype.find` with the behaviour of `Array.prototype.findIndex`), I can change `_nextSecond` it to use `.findIndex` like the the other `_next*` methods, which will hopefully work around the problem.

Also thanks for the other suggestions, as you say any cron expression can't trigger more often than once a second, so I can add a check to enforce that, and add a property for the original cron string and some `toString()` methods.

**Comment by Steve-Mcl** [comment]
Thanks for the consideration & speedy response.

I fully understand that Array is now es6 & shouldn't be overridden - but in this particular instance they were & it had a bad negative side effect on your lib (triggering at tick speed).  

Cheers.
