### ISSUE TITLE
`{ timezone: 'UTC' }` causes unlimited tasks to be fired in certain cases

### ISSUE THREAD

**Issue by jgonera** [jaclarke/cronosjs#27]
```typescript
scheduleTask(
  // 12am UTC, everyday
  '0 0 * * *',
  () => {
    console.log('hello');
  },
  { timezone: 'UTC' },
);
```

Expected result: nothing printed out unless it's midnight UTC.
Actual result: a flurry of hellos!

BTW Thank you for this package! Seems like a great zero-dependency alternative to `node-cron` and `node-schedule`. Have you thought about posting about it on HN, Reddit, etc.?

**Comment by jaclarke** [comment]
I can't seem to be able to reproduce this issue. Does it happen only on specific cron expressions, or dates/times?

**Comment by jgonera** [comment]
Thank you for a quick reply! I updated to 1.7.1 and it seems to be fixed. My guess is that it was caused by midnight being returned as `24:00:00` which was fixed in https://github.com/jaclarke/cronosjs/commit/4818c65ee0863317da54f32857dd65b08d249560

Sorry for a false alarm.
