### ISSUE TITLE
Support for ? Option

### ISSUE THREAD

**Issue by Steve-Mcl** [jaclarke/cronosjs#5]
Hi once again. 

I was wondering if you had any intention of adding support for `?` in your library?
 > Question marks are used to specify 'no specific value' and is allowed for the day-of-month and day-of-week fields. It is used instead of the asterisk (*) for leaving either day-of-month or day-of-week blank.

Reference: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc01963.0510/doc/html/psh1360346725201.html

Some info on the ? Situation...
> ? ("no specific value") - useful when you need to specify something in one of the two fields in which the character is allowed, but not the other. For example, if I want my trigger to fire on a particular day of the month (say, the 10th), but don't care what day of the week that happens to be, I would put "10" in the day-of-month field, and "?" in the day-of-week field

As always, thank you for your continued support and excellent work. Steve.

**Comment by jaclarke** [comment]
The `*` symbol in the 'day of month' and 'day of week' fields currently already behaves as 'no specific value'. Admittedly, looking at the current documentation for the `*` symbol, it's listed as being an 'all values' symbol, and it could be made clearer that its behavior in the *'day of ...'* fields is more of an 'any value'.

Anyway, in answer to your question, yes, I don't see any problem in supporting the `?` symbol in the 'day of ...' fields (essentially as a alias to the `*` symbol).
